#pragma kernel CSMain

struct Circle
{
    float3 Position;
    float Radius;
};

float2 WorldScale;
RWStructuredBuffer<Circle> Circles; 
RWTexture2D<float4> Result;

[numthreads(8,1,1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float4 res = 0;
    res.x += WorldScale.x;

    uint circleCount, _;
    Circles.GetDimensions(circleCount, _);
    for(int i = 0; i < circleCount; i++)
    {
        Circle circle = Circles[i];
        res.z += 1 * circle.Radius / circleCount;
    }
    Result[id.xy] = res;
}
